@hostname = http://localhost
@port = 3000
@controller = seed
@host = {{hostname}}:{{port}}/api/{{controller}}
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI1ZjI5MzIxLWU5YzgtNDNiMS05MDM3LTVlMzcxY2ZkMzhiOSIsImVtYWlsIjoicm9vdC5hZG1pbkBlbWFpbC5jb20iLCJmdWxsTmFtZSI6InJvb3QgYWRtaW4iLCJpYXQiOjE3Mjg4NTg0MjgsImV4cCI6MTcyODg2NTYyOH0.hBsmYfgR_tUsHluhfJRjvMPTObU0PSiIem-JKW2hhs8

### Crear base de datos
GET {{host}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Iniciar sesión
# @name login
POST {{hostname}}:{{port}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "root.admin@email.com",
  "password": "Carro12+"
}