@baseUrl = http://localhost:3000/api
@name = files
### Crear base de datos
POST {{baseUrl}}/{{name}}/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"
Content-Type: image/jpeg

<@ ./dragon.jpeg 

# Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryqTqCcMZdMJjwCr6D
# Content-Disposition: form-data; name="file";"
# Content-Type: image/jpeg


### Otra forma
curl -X POST http://localhost:3000/api/files/upload \
  -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryqTqCcMZdMJjwCr6D' \
  -F 'file=@dragon.jpeg'

###
POST /api/files/upload HTTP/1.1
User-Agent: vscode-restclient
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryqTqCcMZdMJjwCr6D
Content-Disposition: form-data; name="file"
Host: localhost:3000

<@ ./dragon.jpeg 

