@hostname = http://localhost
@port = 3000
@controller = auth
@host = {{hostname}}:{{port}}/api/{{controller}}
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI0ZjZiNTA1LTAzZWItNDA5Zi04Nzg3LWZhNDg3MjViNTdjMyIsImVtYWlsIjoicm9vdC5hZG1pbkBlbWFpbC5jb20iLCJmdWxsTmFtZSI6InJvb3QgYWRtaW4iLCJpYXQiOjE3Mjg4NTg5MjMsImV4cCI6MTcyODg2NjEyM30.vllvLO6riipssSjktkrS_cTN6JLWnJF44AQt3IViQgQ
@userID=ab32e5b0-ab4e-4db8-8049-4497ac43d13e

### Iniciar sesión
# @name login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "root.admin@email.com",
  "password": "Carro12+"
}

### Lista de usuarios
# @name getAll
GET {{host}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### Obtener un usuario
# @name findById
GET {{host}}/{{userID}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Crear usuario
# @name createUser
POST {{host}}/register HTTP/1.1
Content-Type: application/json

{
  "firstName": "root 4",
  "lastName": "admin",
  "email": "rooaawsspest2.admin@email.com",
  "phone": "04121234567",
  "password": "Carro12+"
}


### Actualizar usuario
# @name update
PATCH {{host}}/{{userID}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "lastName": "vader"
}


### Eliminar usuario
# @name remove
DELETE {{host}}/55a1f7f3-1b8e-48dc-a190-45fd846640cf HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### Cambiar el status del usuario
PATCH {{host}}/status/{{userID}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "isActive": "true"
}


### Cambiar roles del usuario
# @name changeRoles
PATCH {{host}}/roles/{{userID}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "roles": ["collaborator", "root", "admin"]
}


### Agregar un role al usuario
# @name addRole
PATCH {{host}}/roles/add/{{userID}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "role": "guest"
}