### hello world
GET http://localhost:3000/api

### Lista de productos
GET http://localhost:3000/api/products

### Lista paginada de productos
GET http://localhost:3000/api/products/pag?limit=2

### Obtener un producto
GET http://localhost:3000/api/products/16e16110-f44f-44f2-b1c0-5a97e9d8148c

### Obtener un producto por TERM: Uuid
GET http://localhost:3000/api/products/term/a84af8af-54b9-4185-be9b-f5421a8e06d9

### Obtener un producto por TERM: slug
GET http://localhost:3000/api/products/term/queso_mozzarella

### Obtener un producto por TEXTO: Uuid
GET http://localhost:3000/api/products/text/a84af8af-54b9-4185-be9b-f5421a8e06d9

### Obtener un producto por TEXTO: slug
GET http://localhost:3000/api/products/text/queso_mozzarella

### Obtener un producto por TEXTO: titulo
GET http://localhost:3000/api/products/text/Queso telita

### Eliminar un producto
DELETE  http://localhost:3000/api/products/73e35552-f6ac-44f5-8d4e-097c73e4389b

### Crear un producto
POST http://localhost:3000/api/products HTTP/1.1
Content-Type: application/json

{
  "title": "Queso ahumado",
  "price": 8
}

