@hostname = http://localhost
@port = 3000
@controller = products
@hostBase = {{hostname}}:{{port}}/api
@host = {{hostBase}}/{{controller}}
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyZDVmMjE0LTY2NmEtNGE4YS1iNmI3LWYxMjEzZjA1NDI0ZSIsImVtYWlsIjoicm9vdC5hZG1pbkBlbWFpbC5jb20iLCJmdWxsTmFtZSI6InJvb3QgYWRtaW4iLCJpYXQiOjE3Mjg4NDk3NzEsImV4cCI6MTcyODg1Njk3MX0.MIVpt2ZichXSgB8iyTDOiEApCpTnHPhS3vhk0jZOn9Q



### hello world
GET {{hostBase}}

### Lista de productos
GET {{host}}
Content-Type: application/json

### Lista paginada de productos
GET {{host}}/pag?limit=2
Content-Type: application/json

### Lista filtrada de productos por titulo
GET {{host}}/by-title?name=queso
Content-Type: application/json

### Lista filtrada de productos por precio
GET {{host}}/by-price?price=8&operator=GT
Content-Type: application/json

### Obtener un producto
GET {{host}}/16e16110-f44f-44f2-b1c0-5a97e9d8148c
Content-Type: application/json

### Obtener un producto por TERM: Uuid
GET {{host}}/term/a84af8af-54b9-4185-be9b-f5421a8e06d9
Content-Type: application/json

### Obtener un producto por TERM: slug
GET {{host}}/term/queso_mozzarella
Content-Type: application/json

### Obtener un producto por TEXTO: Uuid
GET {{host}}/text/a84af8af-54b9-4185-be9b-f5421a8e06d9
Content-Type: application/json

### Obtener un producto por TEXTO: slug
GET {{host}}/text/queso_mozzarella
Content-Type: application/json

### Obtener un producto por TEXTO: titulo
GET {{host}}/text/Queso telita
Content-Type: application/json

### Eliminar un producto
DELETE  {{host}}/be18e6c1-af8a-4016-ad0e-a57a0842148e
Content-Type: application/json

### Crear un producto
POST {{host}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Queso duro llanero churro 9",
  "price": 10,
  "priceSale": 13.99,
  "stock": 10,
  "images": [
    "http://image1.jgp",
    "http://image2.jgp"
  ]
}

### Actualizar un producto
PATCH  {{host}}/be18e6c1-af8a-4016-ad0e-a57a0842148e
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "unit": "kg",
  "images": ["http://image5.jgp"]
}

### Actualizar un producto Error con el titulo
PATCH  {{host}}/a84af8af-54b9-4185-be9b-f5421a8e06d9
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Queso telita"
}

### Actualizar un producto: Agregar tag
PATCH  {{host}}/4420a19a-f23a-4c81-b463-8c25f7ed62cc
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "tags": ["suave", "queso", "perro"],
  "stock": 10
}

### Iniciar sesión
# @name login
POST {{hostBase}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "root.admin@email.com",
  "password": "Carro12+"
}