### hello world
GET http://localhost:3000/api

### Lista de productos
GET http://localhost:3000/api/products

### Lista paginada de productos
GET http://localhost:3000/api/products/pag?limit=2

### Lista filtrada de productos por titulo
GET http://localhost:3000/api/products/by-title?title=jamon

### Lista filtrada de productos por precio
GET http://localhost:3000/api/products/by-price?price=10&operator=GT

### Obtener un producto
GET http://localhost:3000/api/products/16e16110-f44f-44f2-b1c0-5a97e9d8148c

### Obtener un producto por TERM: Uuid
GET http://localhost:3000/api/products/term/a84af8af-54b9-4185-be9b-f5421a8e06d9

### Obtener un producto por TERM: slug
GET http://localhost:3000/api/products/term/queso_mozzarella

### Obtener un producto por TEXTO: Uuid
GET http://localhost:3000/api/products/text/a84af8af-54b9-4185-be9b-f5421a8e06d9

### Obtener un producto por TEXTO: slug
GET http://localhost:3000/api/products/text/queso_mozzarella

### Obtener un producto por TEXTO: titulo
GET http://localhost:3000/api/products/text/Queso telita

### Eliminar un producto
DELETE  http://localhost:3000/api/products/be18e6c1-af8a-4016-ad0e-a57a0842148e

### Crear un producto
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "title": "Salchichas tipo viena",
  "price": 5,
  "stock": 10,
  "images": [
    "http://image1.jgp",
    "http://image2.jgp"
  ]
}

### Actualizar un producto
PATCH  http://localhost:3000/api/products/be18e6c1-af8a-4016-ad0e-a57a0842148e
Content-Type: application/json

{
  "unit": "kg",
  "images": ["http://image5.jgp"]
}

### Actualizar un producto Error con el titulo
PATCH  http://localhost:3000/api/products/a84af8af-54b9-4185-be9b-f5421a8e06d9
Content-Type: application/json

{
  "title": "Queso telita"
}

### Actualizar un producto: Agregar tag
PATCH  http://localhost:3000/api/products/a84af8af-54b9-4185-be9b-f5421a8e06d9
Content-Type: application/json

{
  "tags": ["suave", "queso", "perro"],
  "stock": 10
}